name: GLideN64

on: [push, pull_request, workflow_dispatch]

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        image: ["GLideN64 (x86 PJ64Legacy-Qt)"]
    env:
      QTDIR_x86: C:\Static_Qt_x86
      QT_BUILD_BASE_URL: https://github.com/gonetz/GLideN64/releases/download/qt_build/
      QT_BUILD_x86: qt-5_15-x86-msvc2017-static
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-zlib
      - name: Prepare Environment
        run: |
          $env:revision = git rev-parse --short HEAD
          echo "PJ64PluginsDirQT=$pwd\build\windows-project64-qt\" >> $env:GITHUB_ENV
          echo "GIT_REVISION=$env:revision" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Prepare Qt x86 Builds
        if: ${{ matrix.image == 'GLideN64 (x86 PJ64Legacy-Qt)' }}
        run: |
          curl -L -o %QT_BUILD_x86%.7z %QT_BUILD_BASE_URL%/%QT_BUILD_x86%.7z
          7z x -o%QTDIR_x86% %QT_BUILD_x86%.7z
        shell: cmd
      - name: Compile Translations
        if: ${{ matrix.image == 'GLideN64 (x86 PJ64Legacy-Qt)' }}
        run: |
          set QTDIR=%QTDIR_x86%\%QT_BUILD_x86%
          for %%f in (translations\*.ts) do "%QTDIR%\bin\lrelease.exe" %%f
          move /y translations\*.qm translations\release\
        shell: cmd
      - name: Build GLideN64 (x86 PJ64Legacy-Qt)
        if: ${{ matrix.image == 'GLideN64 (x86 PJ64Legacy-Qt)' }}
        run: |
          set QTDIR=%QTDIR_x86%\%QT_BUILD_x86%
          msbuild projects/msvc/GLideN64.sln /m /p:Configuration=Release_qt_legacy;Platform=Win32
          copy ini\GLideN64.custom.ini %PJ64PluginsDirQT%
          copy translations\release\*.qm %PJ64PluginsDirQT%
        shell: cmd
      - name: Upload GLideN64 (x86 PJ64Legacy-Qt)
        uses: actions/upload-artifact@v4
        if: ${{ matrix.image == 'GLideN64 (x86 PJ64Legacy-Qt)' }}
        with:
          name: GLideN64-${{ env.GIT_REVISION }}-Windows-PJ64Legacy-Qt-x86
          path: |
            build\windows-project64-qt\*.dll
            build\windows-project64-qt\GLideN64.custom.ini
            build\windows-project64-qt\*.qm
  Release:
    runs-on: ubuntu-latest
    needs: [Windows]
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      # sadly we can't download the artifacts without extracting it
      # so re-zip them
      - name: Re-Package Artifacts
        run: |
          cd artifacts
          for artifact in *
          do
            echo "-> Creating ${artifact}.zip"
            pushd "$artifact"
            zip -r "../${artifact}.zip" *
            popd
          done
      - name: Update Git Tag
        run: |
          git tag -f github-actions
          git push -f origin github-actions
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: false
          tag: github-actions
          artifacts: "artifacts/*.zip"
